//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWebServiceTest.WebService1March7Soap")]
    public interface WebService1March7Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponse HelloWorld(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponse> HelloWorldAsync(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AddTwoIntsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoInts", ReplyAction="*")]
        WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponse AddTwoInts(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoInts", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponse> AddTwoIntsAsync(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoIntsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoInts", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequestBody Body;
        
        public AddTwoIntsRequest() {
        }
        
        public AddTwoIntsRequest(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoIntsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int valA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int valB;
        
        public AddTwoIntsRequestBody() {
        }
        
        public AddTwoIntsRequestBody(int valA, int valB) {
            this.valA = valA;
            this.valB = valB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoIntsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoIntsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponseBody Body;
        
        public AddTwoIntsResponse() {
        }
        
        public AddTwoIntsResponse(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoIntsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTwoIntsResult;
        
        public AddTwoIntsResponseBody() {
        }
        
        public AddTwoIntsResponseBody(string AddTwoIntsResult) {
            this.AddTwoIntsResult = AddTwoIntsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1March7SoapChannel : WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1March7SoapClient : System.ServiceModel.ClientBase<WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap>, WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap {
        
        public WebService1March7SoapClient() {
        }
        
        public WebService1March7SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1March7SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1March7SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1March7SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponse WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap.HelloWorld(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest inValue = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequestBody();
            WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponse retVal = ((WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponse> WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap.HelloWorldAsync(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest inValue = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.HelloWorldRequestBody();
            return ((WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponse WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap.AddTwoInts(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest request) {
            return base.Channel.AddTwoInts(request);
        }
        
        public string AddTwoInts(int valA, int valB) {
            WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest inValue = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequestBody();
            inValue.Body.valA = valA;
            inValue.Body.valB = valB;
            WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponse retVal = ((WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap)(this)).AddTwoInts(inValue);
            return retVal.Body.AddTwoIntsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponse> WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap.AddTwoIntsAsync(WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest request) {
            return base.Channel.AddTwoIntsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsResponse> AddTwoIntsAsync(int valA, int valB) {
            WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest inValue = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.AddTwoIntsRequestBody();
            inValue.Body.valA = valA;
            inValue.Body.valB = valB;
            return ((WindowsFormsWebServicesTest.ServiceReferenceWebServiceTest.WebService1March7Soap)(this)).AddTwoIntsAsync(inValue);
        }
    }
}
