//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsWebServicesTest.ServiceReference1Second {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1Second.WebService1March7Soap")]
    public interface WebService1March7Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponse HelloWorld(WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponse> HelloWorldAsync(WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AddTwoIntsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoInts", ReplyAction="*")]
        WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponse AddTwoInts(WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoInts", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponse> AddTwoIntsAsync(WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest request);
        
        // CODEGEN: Generating message contract since element name MultiplyTwoIntsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyTwoInts", ReplyAction="*")]
        WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponse MultiplyTwoInts(WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyTwoInts", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponse> MultiplyTwoIntsAsync(WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoIntsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoInts", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequestBody Body;
        
        public AddTwoIntsRequest() {
        }
        
        public AddTwoIntsRequest(WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoIntsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int valA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int valB;
        
        public AddTwoIntsRequestBody() {
        }
        
        public AddTwoIntsRequestBody(int valA, int valB) {
            this.valA = valA;
            this.valB = valB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoIntsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoIntsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponseBody Body;
        
        public AddTwoIntsResponse() {
        }
        
        public AddTwoIntsResponse(WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoIntsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTwoIntsResult;
        
        public AddTwoIntsResponseBody() {
        }
        
        public AddTwoIntsResponseBody(string AddTwoIntsResult) {
            this.AddTwoIntsResult = AddTwoIntsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplyTwoIntsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplyTwoInts", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequestBody Body;
        
        public MultiplyTwoIntsRequest() {
        }
        
        public MultiplyTwoIntsRequest(WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplyTwoIntsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int valX;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int valY;
        
        public MultiplyTwoIntsRequestBody() {
        }
        
        public MultiplyTwoIntsRequestBody(int valX, int valY) {
            this.valX = valX;
            this.valY = valY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplyTwoIntsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplyTwoIntsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponseBody Body;
        
        public MultiplyTwoIntsResponse() {
        }
        
        public MultiplyTwoIntsResponse(WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplyTwoIntsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MultiplyTwoIntsResult;
        
        public MultiplyTwoIntsResponseBody() {
        }
        
        public MultiplyTwoIntsResponseBody(string MultiplyTwoIntsResult) {
            this.MultiplyTwoIntsResult = MultiplyTwoIntsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1March7SoapChannel : WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1March7SoapClient : System.ServiceModel.ClientBase<WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap>, WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap {
        
        public WebService1March7SoapClient() {
        }
        
        public WebService1March7SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1March7SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1March7SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1March7SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponse WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap.HelloWorld(WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest inValue = new WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequestBody();
            WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponse retVal = ((WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponse> WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap.HelloWorldAsync(WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest inValue = new WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReference1Second.HelloWorldRequestBody();
            return ((WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponse WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap.AddTwoInts(WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest request) {
            return base.Channel.AddTwoInts(request);
        }
        
        public string AddTwoInts(int valA, int valB) {
            WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest inValue = new WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequestBody();
            inValue.Body.valA = valA;
            inValue.Body.valB = valB;
            WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponse retVal = ((WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap)(this)).AddTwoInts(inValue);
            return retVal.Body.AddTwoIntsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponse> WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap.AddTwoIntsAsync(WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest request) {
            return base.Channel.AddTwoIntsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsResponse> AddTwoIntsAsync(int valA, int valB) {
            WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest inValue = new WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReference1Second.AddTwoIntsRequestBody();
            inValue.Body.valA = valA;
            inValue.Body.valB = valB;
            return ((WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap)(this)).AddTwoIntsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponse WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap.MultiplyTwoInts(WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest request) {
            return base.Channel.MultiplyTwoInts(request);
        }
        
        public string MultiplyTwoInts(int valX, int valY) {
            WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest inValue = new WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequestBody();
            inValue.Body.valX = valX;
            inValue.Body.valY = valY;
            WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponse retVal = ((WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap)(this)).MultiplyTwoInts(inValue);
            return retVal.Body.MultiplyTwoIntsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponse> WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap.MultiplyTwoIntsAsync(WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest request) {
            return base.Channel.MultiplyTwoIntsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsResponse> MultiplyTwoIntsAsync(int valX, int valY) {
            WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest inValue = new WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequest();
            inValue.Body = new WindowsFormsWebServicesTest.ServiceReference1Second.MultiplyTwoIntsRequestBody();
            inValue.Body.valX = valX;
            inValue.Body.valY = valY;
            return ((WindowsFormsWebServicesTest.ServiceReference1Second.WebService1March7Soap)(this)).MultiplyTwoIntsAsync(inValue);
        }
    }
}
